name: Generate PDF

on:
  push:
    branches: [ "main" ] # or your default branch name

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # or your specific version
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc 
        
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 
        
    - name: Generate PDF
      run: python make.py
      
    - uses: stefanzweifel/git-auto-commit-action@v5
